apiVersion: v1
kind: Service
metadata:
  name: {{ include "cullis.broker.fullname" . }}
  labels:
    {{- include "cullis.broker.labels" . | nindent 4 }}
  {{- with .Values.broker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - name: http
      port: {{ .Values.broker.service.port }}
      targetPort: http
      protocol: TCP
      {{- if .Values.broker.prometheusEnabled }}
      appProtocol: http
      {{- end }}
  selector:
    {{- include "cullis.broker.selectorLabels" . | nindent 4 }}
