apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cullis.broker.configMapName" . }}
  labels:
    {{- include "cullis.broker.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.broker.environment | quote }}
  LOG_FORMAT: {{ .Values.broker.logFormat | quote }}
  BROKER_HOST: "0.0.0.0"
  BROKER_PORT: {{ .Values.broker.containerPort | quote }}
  {{- if .Values.ingress.enabled }}
  BROKER_PUBLIC_URL: {{ printf "%s://%s" (ternary "https" "http" .Values.ingress.tls.enabled) .Values.ingress.host | quote }}
  {{- end }}

  PROMETHEUS_ENABLED: {{ .Values.broker.prometheusEnabled | quote }}

  {{- if .Values.jaeger.enabled }}
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "cullis-broker"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ printf "http://%s:%v" (include "cullis.jaeger.fullname" .) .Values.jaeger.otlpGrpcPort | quote }}
  OTEL_EXPORTER_INSECURE: "true"
  {{- else }}
  OTEL_ENABLED: "false"
  {{- end }}

  KMS_BACKEND: {{ .Values.vault.kmsBackend | quote }}
  VAULT_ADDR: {{ include "cullis.vaultAddr" . | quote }}
  VAULT_SECRET_PATH: {{ .Values.vault.secretPath | quote }}
