{{- if .Values.redis.internal }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cullis.redis.fullname" . }}
  labels:
    {{- include "cullis.redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "cullis.redis.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "cullis.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cullis.redis.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "cullis.redis.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.redis.storageClassName }}
        storageClassName: {{ .Values.redis.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storageSize }}
{{- end }}
