{{- if .Values.vault.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cullis.vault.fullname" . }}
  labels:
    {{- include "cullis.vault.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: vault
      port: {{ .Values.vault.port }}
      targetPort: vault
      protocol: TCP
  selector:
    {{- include "cullis.vault.selectorLabels" . | nindent 4 }}
{{- end }}
