{{- if .Values.vault.internal }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cullis.vault.fullname" . }}
  labels:
    {{- include "cullis.vault.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "cullis.vault.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "cullis.vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cullis.vault.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vault
          image: {{ .Values.vault.image }}
          imagePullPolicy: IfNotPresent
          args:
            - "server"
            - "-dev"
            - "-dev-listen-address=0.0.0.0:{{ .Values.vault.port }}"
            - "-dev-root-token-id={{ .Values.vault.devRootToken }}"
          ports:
            - name: vault
              containerPort: {{ .Values.vault.port }}
              protocol: TCP
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.devRootToken | quote }}
            - name: VAULT_ADDR
              value: "http://127.0.0.1:{{ .Values.vault.port }}"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&uninitcode=204&sealedcode=204
              port: vault
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&uninitcode=204&sealedcode=204
              port: vault
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /vault/file
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "cullis.vault.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.vault.storageClassName }}
        storageClassName: {{ .Values.vault.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.vault.storageSize }}
{{- end }}
