"""Guardian audit row writer.

Thin wrapper on top of ``mcp_proxy.local.audit.append_local_audit`` so
guardian decisions land on the same per-org hash-chained ``local_audit``
table the rest of the proxy already uses. This keeps the audit format
unified (positive consequence #3 in ADR-016) and avoids a second hash
chain implementation.

All guardian rows use ``event_type="guardian.inspect"``; the
``details`` JSON carries the guardian-specific fields. The dashboard
audit timeline can filter by ``event_type LIKE 'guardian.%'`` once
Phase 6 ships the UI.
"""
from __future__ import annotations

from typing import Any

from mcp_proxy.local.audit import append_local_audit

GUARDIAN_EVENT_TYPE = "guardian.inspect"


async def record_inspection(
    *,
    audit_id: str,
    decision: str,
    direction: str,
    agent_id: str,
    peer_agent_id: str,
    msg_id: str,
    org_id: str | None = None,
    reasons: list[dict[str, Any]] | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Persist one guardian decision. Returns the audit row summary.

    ``audit_id`` is generated by the caller (typically a ULID) so the
    signed ticket can carry it before the row is committed. ``reasons``
    is a list of per-tool match records (``{tool, match}``) for ops
    triage. ``extra`` allows callers to attach arbitrary diagnostic
    fields without bloating the function signature.
    """
    details: dict[str, Any] = {
        "audit_id": audit_id,
        "decision": decision,
        "direction": direction,
        "peer_agent_id": peer_agent_id,
        "msg_id": msg_id,
        "reasons": reasons or [],
    }
    if extra:
        details.update(extra)

    return await append_local_audit(
        event_type=GUARDIAN_EVENT_TYPE,
        result="ok" if decision == "pass" else decision,
        agent_id=agent_id,
        org_id=org_id,
        details=details,
    )
